config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :docs 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
     if @doc.update(doc_params)
       redirect_to @doc
     else
       render 'edit'
     end
   end

   def destroy
     @doc.destroy
     redirect_to docs_path
   end

   private

   def find_doc
     @doc = Doc.find(params[:id])
   end

   def doc_params
     params.require(:doc).permit(:title, :content)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/docs/edit.html.haml
%h2 Fix Doc!
= render "form"
= link_to "Cancel", docs_path

app/views/docs/index.html.haml
- @docs.each do |doc|
  %h2= link_to doc.title, doc
  %p= time_ago_in_words(doc.created_at)
  %p= truncate(doc.content, length:50)

= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
%h2 New Doc!
= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content
= link_to 'All Docs', docs_path
= link_to 'Fix Doc', edit_doc_path(@doc)
= link_to 'Trash It', doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageFile</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
%html
%head
  %title ManageFile | Your life's work!
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to " ManageFile ", root_path, id: "logo"

      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path


  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.haml
#bunner
  .bunner_content
    %h1 ManageFile
    %p Your life's work. Organized, always.

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Enamel pin flannel kitsch selfies tbh tote bag. Ethical yr vexillologist, fanny pack gastropub tote bag VHS. Vegan letterpress lyft paleo, shabby chic fixie drinking vinegar echo park chartreuse kickstarter photo booth vape pok pok offal. Next level kickstarter ugh mixtape, celiac paleo small batch fixie PBR&B tilde blue bottle edison bulb tousled poutine.
#bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br